# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Timeout for commands executed by starship (in milliseconds).# Timeout for commands executed by starship (in milliseconds).# Timeout for commands executed by starship (in milliseconds).
command_timeout = 1000

# Module configurations
# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[V](bold blue) "

[directory]
# truncation_length = 6
truncation_symbol = "…/"

# [git_branch]
# symbol = " "

# [git_status]
# ahead = "⇡${count}"
# diverged = "⇕⇡${ahead_count}⇣${behind_count}"
# behind = "⇣${count}"

# [hg_branch]
# symbol = " "
